import type {
  CategoryListEntry,
  JobTypeGroupRow,
  SubcategoryRow,
} from '../types';

export const PLACEHOLDER_JOB_TYPES: readonly CategoryListEntry[] = [
  {
    id: 'residential-service',
    name: 'Residential Service',
    iconTone: 'blue',
    subcategoryCount: 8,
  },
  {
    id: 'commercial-service',
    name: 'Commercial Service',
    code: 'COMM-SVC',
    iconTone: 'indigo',
  },
  {
    id: 'maintenance-plan',
    name: 'Maintenance Plan',
    iconTone: 'green',
  },
  {
    id: 'emergency',
    name: 'Emergency Response',
    iconTone: 'red',
  },
  {
    id: 'installation',
    name: 'Installation Project',
    iconTone: 'orange',
  },
  {
    id: 'warranty',
    name: 'Warranty Callback',
    iconTone: 'amber',
    inactive: true,
  },
];

export const PLACEHOLDER_CATEGORIES: readonly CategoryListEntry[] = [
  {
    id: 'annual-hvac',
    name: 'Annual HVAC Maintenance',
    iconTone: 'blue',
    subcategoryCount: 12,
  },
  {
    id: 'hvac-repair',
    name: 'HVAC Repair',
    code: 'HVAC-REPR',
    iconTone: 'red',
  },
  {
    id: 'ac-install',
    name: 'AC Installation',
    code: 'AC-INST',
    iconTone: 'green',
  },
  {
    id: 'furnace-install',
    name: 'Furnace Installation',
    iconTone: 'orange',
  },
  {
    id: 'duct-clean',
    name: 'Duct Cleaning',
    iconTone: 'indigo',
  },
  {
    id: 'thermostat',
    name: 'Thermostat Installation',
    iconTone: 'pink',
  },
  {
    id: 'emergency-hvac',
    name: 'Emergency HVAC Service',
    iconTone: 'amber',
    inactive: true,
  },
];

export const PLACEHOLDER_SUBCATEGORIES: readonly SubcategoryRow[] = [
  {
    id: 'sub-1',
    categoryId: 'annual-hvac',
    subcategory: 'AC Maintenance',
    trade: 'HVAC',
    estimatedTime: '2h 00m',
    priority: 'High',
    taskName: 'Filter Check',
    isActive: true,
  },
  {
    id: 'sub-2',
    categoryId: 'annual-hvac',
    subcategory: 'Filter Replacement',
    trade: 'HVAC',
    estimatedTime: '2h 00m',
    priority: 'High',
    taskName: 'Filter Check',
    isActive: true,
  },
  {
    id: 'sub-3',
    categoryId: 'annual-hvac',
    subcategory: 'Gas Filling',
    trade: 'HVAC',
    estimatedTime: '2h 00m',
    priority: 'High',
    taskName: 'Filter Check',
    isActive: true,
  },
  {
    id: 'sub-4',
    categoryId: 'annual-hvac',
    subcategory: 'Coil Cleaning',
    trade: 'HVAC',
    estimatedTime: '1h 30m',
    priority: 'Medium',
    taskName: 'Coil Inspection',
    isActive: true,
  },
  {
    id: 'sub-5',
    categoryId: 'annual-hvac',
    subcategory: 'Blower Service',
    trade: 'HVAC',
    estimatedTime: '1h 00m',
    priority: 'Medium',
    taskName: 'Blower Test',
    isActive: true,
  },
  {
    id: 'sub-6',
    categoryId: 'annual-hvac',
    subcategory: 'Safety Check',
    trade: 'HVAC',
    estimatedTime: '45m',
    priority: 'Low',
    taskName: 'Safety Audit',
    isActive: true,
  },
  {
    id: 'sub-7',
    categoryId: 'annual-hvac',
    subcategory: 'Legacy Tune-up',
    trade: 'HVAC',
    estimatedTime: '3h 00m',
    priority: 'Low',
    taskName: 'Full Tune-up',
    isActive: false,
  },
  {
    id: 'sub-8',
    categoryId: 'hvac-repair',
    subcategory: 'Compressor Repair',
    trade: 'HVAC',
    estimatedTime: '4h 00m',
    priority: 'High',
    taskName: 'Compressor Test',
    isActive: true,
  },
];

const maintenanceSubcategories = PLACEHOLDER_SUBCATEGORIES.filter(
  (row) => row.categoryId === 'annual-hvac' && row.isActive,
).slice(0, 1);

export const PLACEHOLDER_JOB_TYPE_GROUPS: readonly JobTypeGroupRow[] = [
  {
    id: 'maintenance',
    jobType: 'Maintenance',
    category: 'HVAC',
    businessUnit: 'Break 1',
    glAccount: 'GL-HVAC',
    usedFor: 'Preventive',
    taskCount: 1,
    isActive: true,
    subcategories: maintenanceSubcategories,
  },
  {
    id: 'repair',
    jobType: 'Repair',
    category: 'HVAC',
    businessUnit: 'Break 1',
    glAccount: 'GL-HVAC',
    usedFor: 'Corrective',
    taskCount: 1,
    isActive: true,
    subcategories: [],
  },
  {
    id: 'cleaning',
    jobType: 'Cleaning',
    category: 'HVAC',
    businessUnit: 'Break 1',
    glAccount: 'GL-HVAC',
    usedFor: 'Preventive',
    taskCount: 1,
    isActive: true,
    subcategories: [],
  },
  {
    id: 'installation',
    jobType: 'Installation',
    category: 'HVAC',
    businessUnit: 'Break 1',
    glAccount: 'GL-HVAC',
    usedFor: 'New Install',
    taskCount: 1,
    isActive: true,
    subcategories: [],
  },
  {
    id: 'inspection',
    jobType: 'Inspection',
    category: 'HVAC',
    businessUnit: 'Break 1',
    glAccount: 'GL-HVAC',
    usedFor: 'Preventive',
    taskCount: 0,
    isActive: true,
    subcategories: [],
  },
  {
    id: 'legacy',
    jobType: 'Legacy Type',
    category: 'HVAC',
    businessUnit: 'Break 1',
    glAccount: 'GL-HVAC',
    usedFor: 'Corrective',
    taskCount: 0,
    isActive: true,
    subcategories: [],
  },
  {
    id: 'retired',
    jobType: 'Retired Type',
    category: 'HVAC',
    businessUnit: 'Break 1',
    glAccount: 'GL-HVAC',
    usedFor: 'Preventive',
    taskCount: 0,
    isActive: false,
    subcategories: [],
  },
];
