export {
  SETUP_COMPANY_LABEL,
  SETUP_COMPANY_TAB,
  SETUP_OPERATIONS_LABEL,
  SETUP_OPERATIONS_TAB,
  SETUP_PATH,
  SETUP_TAB_STATE_KEY,
  SETUP_USERS_PAYROLL_LABEL,
  SETUP_USERS_PAYROLL_TAB,
} from './setup-path';
