/**
 * Wire request/response contracts for the user MFE catalog resources.
 */
export {
  pagedResultSchema,
  setupResponseSchema,
  type PagedResult,
  type SetupListParams,
  type SortDirection,
} from './lib/envelope.schema';
export {
  userAuthenticationMethodSchema,
  userCreateResponseSchema,
  userDetailDtoSchema,
  userDetailResponseSchema,
  userInviteDtoSchema,
  userListResponseSchema,
  userListResultDtoSchema,
  userListSummaryDtoSchema,
  userPatchDtoSchema,
  userSummaryDtoSchema,
  userUpdateDtoSchema,
  type UserAuthenticationMethod,
  type UserDetailDto,
  type UserInviteDto,
  type UserListParams,
  type UserListResult,
  type UserListResultDto,
  type UserListSummaryDto,
  type UserPatchDto,
  type UserSummaryDto,
  type UserUpdateDto,
} from './lib/user.schema';
export {
  userRoleCreateDtoSchema,
  userRoleDetailDtoSchema,
  userRoleDetailResponseSchema,
  userRoleListResponseSchema,
  userRoleLookupDtoSchema,
  userRoleLookupResponseSchema,
  userRolePatchDtoSchema,
  userRoleSyncDtoSchema,
  userRoleUpdateDtoSchema,
  type UserRoleCreateDto,
  type UserRoleDetailDto,
  type UserRoleLookupDto,
  type UserRoleLookupParams,
  type UserRolePatchDto,
  type UserRoleSyncDto,
  type UserRoleUpdateDto,
} from './lib/user-role.schema';
export {
  roleCloneDtoSchema,
  roleCreateDtoSchema,
  roleDetailDtoSchema,
  roleDetailResponseSchema,
  roleListResponseSchema,
  roleLookupDtoSchema,
  roleLookupResponseSchema,
  rolePatchDtoSchema,
  roleSummaryDtoSchema,
  roleUpdateDtoSchema,
  type RoleCloneDto,
  type RoleCreateDto,
  type RoleDetailDto,
  type RoleListParams,
  type RoleLookupDto,
  type RolePatchDto,
  type RoleSummaryDto,
  type RoleUpdateDto,
} from './lib/role.schema';
