export {
  ACTIVE_LABEL,
  BUSINESS_TYPE_PAGE_SIZE,
  EMPTY_BUSINESS_TYPES_MESSAGE,
  ENABLE_SUCCESS_MESSAGE,
  INACTIVE_LABEL,
  LOADING_BUSINESS_TYPES_LABEL,
  PAGE_DESCRIPTION,
  PAGE_TITLE,
} from './copy';
