/**
 * Wire request/response contracts for the settings MFE catalog resources.
 * Data-access, MSW, and UI all import from here — do not duplicate DTOs.
 */
export {
  pagedResultSchema,
  setupResponseSchema,
  type PagedResult,
  type SetupListParams,
  type SortDirection,
} from './lib/envelope.schema';
export {
  companyAddressDtoSchema,
  companyDetailResponseSchema,
  companyDtoSchema,
  companyPatchDtoSchema,
  type CompanyAddressDto,
  type CompanyDto,
  type CompanyPatchDto,
} from './lib/company.schema';
export {
  taxCreateDtoSchema,
  taxDetailDtoSchema,
  taxDetailResponseSchema,
  taxLineDetailDtoSchema,
  taxListResponseSchema,
  taxLookupDtoSchema,
  taxLookupResponseSchema,
  taxPatchDtoSchema,
  taxSummaryDtoSchema,
  taxUpdateDtoSchema,
  type TaxCreateDto,
  type TaxDetailDto,
  type TaxLineDetailDto,
  type TaxListParams,
  type TaxLookupDto,
  type TaxPatchDto,
  type TaxSummaryDto,
  type TaxUpdateDto,
} from './lib/tax.schema';
export {
  taxAuthorityCreateDtoSchema,
  taxAuthorityDetailDtoSchema,
  taxAuthorityDetailResponseSchema,
  taxAuthorityListResponseSchema,
  taxAuthorityLookupDtoSchema,
  taxAuthorityLookupResponseSchema,
  taxAuthorityPatchDtoSchema,
  taxAuthoritySummaryDtoSchema,
  taxAuthorityUpdateDtoSchema,
  type TaxAuthorityCreateDto,
  type TaxAuthorityDetailDto,
  type TaxAuthorityListParams,
  type TaxAuthorityLookupDto,
  type TaxAuthorityPatchDto,
  type TaxAuthoritySummaryDto,
  type TaxAuthorityUpdateDto,
} from './lib/tax-authority.schema';
export {
  postalCodeCreateDtoSchema,
  postalCodeDetailDtoSchema,
  postalCodeDetailResponseSchema,
  postalCodeListResponseSchema,
  postalCodeLookupDtoSchema,
  postalCodeLookupResponseSchema,
  postalCodePatchDtoSchema,
  postalCodeSummaryDtoSchema,
  postalCodeUpdateDtoSchema,
  type PostalCodeCreateDto,
  type PostalCodeDetailDto,
  type PostalCodeListParams,
  type PostalCodeLookupDto,
  type PostalCodePatchDto,
  type PostalCodeSummaryDto,
  type PostalCodeUpdateDto,
} from './lib/postal-code.schema';
export {
  nonWorkingDateCreateDtoSchema,
  nonWorkingDateDetailDtoSchema,
  nonWorkingDateDetailResponseSchema,
  nonWorkingDateListResponseSchema,
  nonWorkingDateLookupDtoSchema,
  nonWorkingDateLookupResponseSchema,
  nonWorkingDatePatchDtoSchema,
  nonWorkingDateSummaryDtoSchema,
  nonWorkingDateUpdateDtoSchema,
  type NonWorkingDateCreateDto,
  type NonWorkingDateDetailDto,
  type NonWorkingDateListParams,
  type NonWorkingDateLookupDto,
  type NonWorkingDatePatchDto,
  type NonWorkingDateSummaryDto,
  type NonWorkingDateUpdateDto,
} from './lib/non-working-date.schema';
export {
  zoneCreateDtoSchema,
  zoneDetailDtoSchema,
  zoneDetailResponseSchema,
  zoneListResponseSchema,
  zoneLookupDtoSchema,
  zoneLookupResponseSchema,
  zonePatchDtoSchema,
  zoneSummaryDtoSchema,
  zoneUpdateDtoSchema,
  type ZoneCreateDto,
  type ZoneDetailDto,
  type ZoneListParams,
  type ZoneLookupDto,
  type ZonePatchDto,
  type ZoneSummaryDto,
  type ZoneUpdateDto,
} from './lib/zone.schema';
export {
  glBreakAddressDetailDtoSchema,
  glBreakCreateDtoSchema,
  glBreakDetailDtoSchema,
  glBreakDetailResponseSchema,
  glBreakListResponseSchema,
  glBreakLocationWriteDtoSchema,
  glBreakLookupDtoSchema,
  glBreakLookupResponseSchema,
  glBreakPatchDtoSchema,
  glBreakSummaryDtoSchema,
  glBreakTradeDtoSchema,
  glBreakUpdateDtoSchema,
  type GlBreakAddressDetailDto,
  type GlBreakCreateDto,
  type GlBreakDetailDto,
  type GlBreakListParams,
  type GlBreakLocationWriteDto,
  type GlBreakLookupDto,
  type GlBreakPatchDto,
  type GlBreakSummaryDto,
  type GlBreakTradeDto,
  type GlBreakUpdateDto,
} from './lib/gl-break.schema';
export {
  techTradeCreateDtoSchema,
  techTradeDetailDtoSchema,
  techTradeDetailResponseSchema,
  techTradeListResponseSchema,
  techTradeLookupDtoSchema,
  techTradeLookupResponseSchema,
  techTradePatchDtoSchema,
  techTradeSummaryDtoSchema,
  techTradeUpdateDtoSchema,
  type TechTradeCreateDto,
  type TechTradeDetailDto,
  type TechTradeListParams,
  type TechTradeLookupDto,
  type TechTradePatchDto,
  type TechTradeSummaryDto,
  type TechTradeUpdateDto,
} from './lib/tech-trade.schema';

export {
  techSkillLevelCreateDtoSchema,
  techSkillLevelDetailDtoSchema,
  techSkillLevelDetailResponseSchema,
  techSkillLevelListResponseSchema,
  techSkillLevelLookupDtoSchema,
  techSkillLevelLookupResponseSchema,
  techSkillLevelPatchDtoSchema,
  techSkillLevelSummaryDtoSchema,
  techSkillLevelUpdateDtoSchema,
  type TechSkillLevelCreateDto,
  type TechSkillLevelDetailDto,
  type TechSkillLevelListParams,
  type TechSkillLevelLookupDto,
  type TechSkillLevelPatchDto,
  type TechSkillLevelSummaryDto,
  type TechSkillLevelUpdateDto,
} from './lib/tech-skill-level.schema';
export {
  businessTypeCreateDtoSchema,
  businessTypeDetailDtoSchema,
  businessTypeDetailResponseSchema,
  businessTypeListResponseSchema,
  businessTypeLookupDtoSchema,
  businessTypeLookupResponseSchema,
  businessTypePatchDtoSchema,
  businessTypeSummaryDtoSchema,
  businessTypeUpdateDtoSchema,
  type BusinessTypeCreateDto,
  type BusinessTypeDetailDto,
  type BusinessTypeListParams,
  type BusinessTypeLookupDto,
  type BusinessTypePatchDto,
  type BusinessTypeSummaryDto,
  type BusinessTypeUpdateDto,
} from './lib/business-type.schema';
