/**
 * Wire request/response contracts for the settings MFE catalog resources.
 * Data-access, MSW, and UI all import from here — do not duplicate DTOs.
 */
export {
  pagedResultSchema,
  setupResponseSchema,
  type PagedResult,
  type SetupListParams,
  type SortDirection,
} from './lib/envelope.schema';
export {
  companyAddressDtoSchema,
  companyDetailResponseSchema,
  companyDtoSchema,
  companyPatchDtoSchema,
  type CompanyAddressDto,
  type CompanyDto,
  type CompanyPatchDto,
} from './lib/company.schema';
export {
  taxCreateDtoSchema,
  taxDetailDtoSchema,
  taxDetailResponseSchema,
  taxLineDetailDtoSchema,
  taxListResponseSchema,
  taxLookupDtoSchema,
  taxLookupResponseSchema,
  taxPatchDtoSchema,
  taxSummaryDtoSchema,
  taxUpdateDtoSchema,
  type TaxCreateDto,
  type TaxDetailDto,
  type TaxLineDetailDto,
  type TaxListParams,
  type TaxLookupDto,
  type TaxPatchDto,
  type TaxSummaryDto,
  type TaxUpdateDto,
} from './lib/tax.schema';
export {
  taxAuthorityCreateDtoSchema,
  taxAuthorityDetailDtoSchema,
  taxAuthorityDetailResponseSchema,
  taxAuthorityListResponseSchema,
  taxAuthorityLookupDtoSchema,
  taxAuthorityLookupResponseSchema,
  taxAuthorityPatchDtoSchema,
  taxAuthoritySummaryDtoSchema,
  taxAuthorityUpdateDtoSchema,
  type TaxAuthorityCreateDto,
  type TaxAuthorityDetailDto,
  type TaxAuthorityListParams,
  type TaxAuthorityLookupDto,
  type TaxAuthorityPatchDto,
  type TaxAuthoritySummaryDto,
  type TaxAuthorityUpdateDto,
} from './lib/tax-authority.schema';
export {
  postalCodeCreateDtoSchema,
  postalCodeDetailDtoSchema,
  postalCodeDetailResponseSchema,
  postalCodeListResponseSchema,
  postalCodeLookupDtoSchema,
  postalCodeLookupResponseSchema,
  postalCodePatchDtoSchema,
  postalCodeSummaryDtoSchema,
  postalCodeUpdateDtoSchema,
  type PostalCodeCreateDto,
  type PostalCodeDetailDto,
  type PostalCodeListParams,
  type PostalCodeLookupDto,
  type PostalCodePatchDto,
  type PostalCodeSummaryDto,
  type PostalCodeUpdateDto,
} from './lib/postal-code.schema';
export {
  nonWorkingDateCreateDtoSchema,
  nonWorkingDateDetailDtoSchema,
  nonWorkingDateDetailResponseSchema,
  nonWorkingDateListResponseSchema,
  nonWorkingDateLookupDtoSchema,
  nonWorkingDateLookupResponseSchema,
  nonWorkingDatePatchDtoSchema,
  nonWorkingDateSummaryDtoSchema,
  nonWorkingDateUpdateDtoSchema,
  type NonWorkingDateCreateDto,
  type NonWorkingDateDetailDto,
  type NonWorkingDateListParams,
  type NonWorkingDateLookupDto,
  type NonWorkingDatePatchDto,
  type NonWorkingDateSummaryDto,
  type NonWorkingDateUpdateDto,
} from './lib/non-working-date.schema';
export {
  zoneCreateDtoSchema,
  zoneDetailDtoSchema,
  zoneDetailResponseSchema,
  zoneListResponseSchema,
  zoneLookupDtoSchema,
  zoneLookupResponseSchema,
  zonePatchDtoSchema,
  zoneSummaryDtoSchema,
  zoneUpdateDtoSchema,
  type ZoneCreateDto,
  type ZoneDetailDto,
  type ZoneListParams,
  type ZoneLookupDto,
  type ZonePatchDto,
  type ZoneSummaryDto,
  type ZoneUpdateDto,
} from './lib/zone.schema';
export {
  glBreakAddressDetailDtoSchema,
  glBreakCreateDtoSchema,
  glBreakDetailDtoSchema,
  glBreakDetailResponseSchema,
  glBreakListResponseSchema,
  glBreakLocationWriteDtoSchema,
  glBreakLookupDtoSchema,
  glBreakLookupResponseSchema,
  glBreakPatchDtoSchema,
  glBreakSummaryDtoSchema,
  glBreakTradeDtoSchema,
  glBreakUpdateDtoSchema,
  type GlBreakAddressDetailDto,
  type GlBreakCreateDto,
  type GlBreakDetailDto,
  type GlBreakListParams,
  type GlBreakLocationWriteDto,
  type GlBreakLookupDto,
  type GlBreakPatchDto,
  type GlBreakSummaryDto,
  type GlBreakTradeDto,
  type GlBreakUpdateDto,
} from './lib/gl-break.schema';
export {
  techTradeCreateDtoSchema,
  techTradeDetailDtoSchema,
  techTradeDetailResponseSchema,
  techTradeListResponseSchema,
  techTradeLookupDtoSchema,
  techTradeLookupResponseSchema,
  techTradePatchDtoSchema,
  techTradeSummaryDtoSchema,
  techTradeUpdateDtoSchema,
  type TechTradeCreateDto,
  type TechTradeDetailDto,
  type TechTradeListParams,
  type TechTradeLookupDto,
  type TechTradePatchDto,
  type TechTradeSummaryDto,
  type TechTradeUpdateDto,
} from './lib/tech-trade.schema';

export {
  techSkillLevelCreateDtoSchema,
  techSkillLevelDetailDtoSchema,
  techSkillLevelDetailResponseSchema,
  techSkillLevelListResponseSchema,
  techSkillLevelLookupDtoSchema,
  techSkillLevelLookupResponseSchema,
  techSkillLevelPatchDtoSchema,
  techSkillLevelSummaryDtoSchema,
  techSkillLevelUpdateDtoSchema,
  type TechSkillLevelCreateDto,
  type TechSkillLevelDetailDto,
  type TechSkillLevelListParams,
  type TechSkillLevelLookupDto,
  type TechSkillLevelPatchDto,
  type TechSkillLevelSummaryDto,
  type TechSkillLevelUpdateDto,
} from './lib/tech-skill-level.schema';
export {
  billingCategoryCreateDtoSchema,
  billingCategoryDetailDtoSchema,
  billingCategoryDetailResponseSchema,
  billingCategoryListResponseSchema,
  billingCategoryLookupDtoSchema,
  billingCategoryLookupResponseSchema,
  billingCategoryPatchDtoSchema,
  billingCategorySummaryDtoSchema,
  billingCategoryUpdateDtoSchema,
  type BillingCategoryCreateDto,
  type BillingCategoryDetailDto,
  type BillingCategoryListParams,
  type BillingCategoryLookupDto,
  type BillingCategoryLookupParams,
  type BillingCategoryPatchDto,
  type BillingCategorySummaryDto,
  type BillingCategoryUpdateDto,
} from './lib/billing-category.schema';
export {
  businessTypeCreateDtoSchema,
  businessTypeDetailDtoSchema,
  businessTypeDetailResponseSchema,
  businessTypeListResponseSchema,
  businessTypeLookupDtoSchema,
  businessTypeLookupResponseSchema,
  businessTypePatchDtoSchema,
  businessTypeSummaryDtoSchema,
  businessTypeUpdateDtoSchema,
  type BusinessTypeCreateDto,
  type BusinessTypeDetailDto,
  type BusinessTypeListParams,
  type BusinessTypeLookupDto,
  type BusinessTypePatchDto,
  type BusinessTypeSummaryDto,
  type BusinessTypeUpdateDto,
} from './lib/business-type.schema';
export {
  jobCategoryCreateDtoSchema,
  jobCategoryDetailDtoSchema,
  jobCategoryDetailResponseSchema,
  jobCategoryListResponseSchema,
  jobCategoryLookupDtoSchema,
  jobCategoryLookupResponseSchema,
  jobCategoryPatchDtoSchema,
  jobCategorySummaryDtoSchema,
  jobCategoryUpdateDtoSchema,
  type JobCategoryCreateDto,
  type JobCategoryDetailDto,
  type JobCategoryListParams,
  type JobCategoryLookupDto,
  type JobCategoryPatchDto,
  type JobCategorySummaryDto,
  type JobCategoryUpdateDto,
} from './lib/job-category.schema';
export {
  jobTypeCountsDtoSchema,
  jobTypeCountsResponseSchema,
  jobTypeCreateDtoSchema,
  jobTypeDetailDtoSchema,
  jobTypeDetailResponseSchema,
  jobTypeListResponseSchema,
  jobTypeLookupDtoSchema,
  jobTypeLookupResponseSchema,
  jobTypePatchDtoSchema,
  jobTypeSubCategoryDtoSchema,
  jobTypeSubCategoryWriteDtoSchema,
  jobTypeSummaryDtoSchema,
  jobTypeUpdateDtoSchema,
  type JobTypeCountsDto,
  type JobTypeCountsParams,
  type JobTypeCreateDto,
  type JobTypeDetailDto,
  type JobTypeListParams,
  type JobTypeLookupDto,
  type JobTypePatchDto,
  type JobTypeSubCategoryDto,
  type JobTypeSubCategoryWriteDto,
  type JobTypeSummaryDto,
  type JobTypeUpdateDto,
} from './lib/job-type.schema';
export {
  subcategoryCreateDtoSchema,
  subcategoryDetailDtoSchema,
  subcategoryDetailResponseSchema,
  subcategoryListResponseSchema,
  subcategoryLookupDtoSchema,
  subcategoryLookupResponseSchema,
  subcategoryPatchDtoSchema,
  subcategorySummaryDtoSchema,
  subcategoryUpdateDtoSchema,
  type SubcategoryCreateDto,
  type SubcategoryDetailDto,
  type SubcategoryListParams,
  type SubcategoryLookupDto,
  type SubcategoryPatchDto,
  type SubcategorySummaryDto,
  type SubcategoryUpdateDto,
} from './lib/subcategory.schema';

export {
  employeeAddressDetailDtoSchema,
  employeeCreateDtoSchema,
  employeeDetailDtoSchema,
  employeeDetailResponseSchema,
  employeeListResponseSchema,
  employeeListResultDtoSchema,
  employeeListSummaryDtoSchema,
  employeeLocationWriteDtoSchema,
  employeeLookupDtoSchema,
  employeeLookupResponseSchema,
  employeePatchDtoSchema,
  employeeSummaryDtoSchema,
  employeeTechnicianProfileDetailDtoSchema,
  employeeTechnicianProfileWriteDtoSchema,
  employeeUpdateDtoSchema,
  type EmployeeAddressDetailDto,
  type EmployeeCreateDto,
  type EmployeeDetailDto,
  type EmployeeListParams,
  type EmployeeListResult,
  type EmployeeListSummaryDto,
  type EmployeeLocationWriteDto,
  type EmployeeLookupDto,
  type EmployeePatchDto,
  type EmployeeSummaryDto,
  type EmployeeTechnicianProfileDetailDto,
  type EmployeeTechnicianProfileWriteDto,
  type EmployeeUpdateDto,
} from './lib/employee.schema';
export {
  resolutionCodeCreateDtoSchema,
  resolutionCodeDetailDtoSchema,
  resolutionCodeDetailResponseSchema,
  resolutionCodeListResponseSchema,
  resolutionCodeLookupDtoSchema,
  resolutionCodeLookupResponseSchema,
  resolutionCodePatchDtoSchema,
  resolutionCodeSummaryDtoSchema,
  resolutionCodeUpdateDtoSchema,
  type ResolutionCodeCreateDto,
  type ResolutionCodeDetailDto,
  type ResolutionCodeListParams,
  type ResolutionCodeLookupDto,
  type ResolutionCodeLookupParams,
  type ResolutionCodePatchDto,
  type ResolutionCodeSummaryDto,
  type ResolutionCodeUpdateDto,
} from './lib/resolution-code.schema';
export {
  timeslotCreateDtoSchema,
  timeslotDetailDtoSchema,
  timeslotDetailResponseSchema,
  timeslotListResponseSchema,
  timeslotLookupDtoSchema,
  timeslotLookupResponseSchema,
  timeslotPatchDtoSchema,
  timeslotSummaryDtoSchema,
  timeslotUpdateDtoSchema,
  type TimeslotCreateDto,
  type TimeslotDetailDto,
  type TimeslotListParams,
  type TimeslotLookupDto,
  type TimeslotLookupParams,
  type TimeslotPatchDto,
  type TimeslotSummaryDto,
  type TimeslotUpdateDto,
} from './lib/timeslot.schema';
export {
  setupDescriptionCreateDtoSchema,
  setupDescriptionDetailDtoSchema,
  setupDescriptionDetailResponseSchema,
  setupDescriptionListResponseSchema,
  setupDescriptionLookupDtoSchema,
  setupDescriptionLookupResponseSchema,
  setupDescriptionPatchDtoSchema,
  setupDescriptionSummaryDtoSchema,
  setupDescriptionUpdateDtoSchema,
  type SetupDescriptionCreateDto,
  type SetupDescriptionDetailDto,
  type SetupDescriptionListParams,
  type SetupDescriptionLookupDto,
  type SetupDescriptionLookupParams,
  type SetupDescriptionPatchDto,
  type SetupDescriptionSummaryDto,
  type SetupDescriptionUpdateDto,
} from './lib/setup-description.schema';
